# -*- coding: utf-8 -*-
import os
import json
from oauth2client.service_account import ServiceAccountCredentials
import gspread

# Authenticate Google API
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive"
]

if "GOOGLE_CREDS" in os.environ:
    creds_dict = json.loads(os.environ["GOOGLE_CREDS"])
    creds = ServiceAccountCredentials.from_json_keyfile_dict(
        creds_dict,
        scope
    )
else:
    creds = ServiceAccountCredentials.from_json_keyfile_name(
        "creds.json",
        scope
    )

client = gspread.authorize(creds)

"""
Automated Penalty Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1era5Xk_O7EfNOTwM8Z8oF2KyxVnR7wwK
"""

seasons = [
    "20212022",
    "20222023",
    "20232024",
    "20242025",
    "20252026",
    "20262027"
]

big10_teams = [
    "mic",
    "msu",
    "osu",
    "min",
    "psu",
    "wis",
    "ndk"
]

import requests
import re
from bs4 import BeautifulSoup

pattern = re.compile(r"/box/final/\d{8}/[a-z]{2,4}/[a-z]{2,4}/")

all_big10_links = []

for season in seasons:
    url = f"https://www.collegehockeynews.com/schedules/?season={season}"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    print(response.status_code, len(response.text))
    print([h.get_text(" ", strip=True) for h in soup.find_all("h2")][:3])

    matches = pattern.findall(soup.prettify())
    full_links = ["https://www.collegehockeynews.com" + m for m in matches]

    # keep games where ANY Big Ten team is home or away
    big10_links = [
        link for link in full_links
        if any(f"/{team}/" in link for team in big10_teams)
    ]

    print(f"{season}: {len(big10_links)} Big Ten games")
    all_big10_links.extend(big10_links)

    all_big10_links = sorted(set(all_big10_links))

print(f"\nTotal unique Big Ten box scores: {len(all_big10_links)}")
# for link in all_big10_links:
#    print(f'"{link}",')

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

# ---------------------------
# Michigan 2024–25 Schedule
# ---------------------------
urls = [link for link in all_big10_links]


all_rows = []

for url in urls:
    print("Scraping", url)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    split_phrase = "Period"
    split_phrase2 = "Overtime"

    # ---------------------------
    # Location
    # ---------------------------
    def get_location():
        if soup.find(string="at Yost Ice Arena, Ann Arbor, Mich."):
            return "Home"
        return "Away"

    # ---------------------------
    # Referees
    # ---------------------------
    referee_names = []
    ref_el = soup.find(string="Referees")
    if ref_el:
        next_text = ref_el.find_next(string=True)
        if next_text:
            referee_names = [r.strip() for r in next_text.strip(":").split(",")]

    while len(referee_names) < 2:
        referee_names.append("")

    # ---------------------------
    # Teams & Date
    # ---------------------------
    h2 = soup.find_all("h2")
    team_text = h2[0].text.split("vs.")

    away_team = team_text[0].strip()
    home_team_and_date = team_text[1].rsplit("-", 1)

    home_team = home_team_and_date[0].replace('\xa0', ' ').strip()
    date = home_team_and_date[1].strip()

    game_id = f"{date}_{home_team}_{away_team}"

    # ---------------------------
    # Conferences
    # ---------------------------
    BigTen = ["Michigan","Michigan State","Minnesota","Notre Dame","Ohio State","Penn State","Wisconsin"]

    if home_team in BigTen:
        home_conf = "Big Ten"
    else:
        home_conf = "Other"

    # ---------------------------
    # Game Type
    # ---------------------------
    game_type = ""
    sub_meta = soup.find(class_='sub-meta')
    if sub_meta:
        span = sub_meta.find('span')
        if span:
            game_type = span.text.strip()

    # ---------------------------
    # Scoring Info
    # ---------------------------
    goal_period = []
    goal_team = []
    goal_clock = []

    scoring_div = soup.find('div', id="scoring")
    if scoring_div:
        tbody = scoring_div.find('tbody')
        if tbody:
            rows = tbody.find_all('tr')
            current_period = "1"

            for row in rows:
                tds = [td.text.strip() for td in row.find_all('td') if td.text.strip()]

                if not tds:
                    continue

                if "Period 1" in tds[0]:
                    current_period = "1"
                elif "Period 2" in tds[0]:
                    current_period = "2"
                elif "Period 3" in tds[0]:
                    current_period = "3"
                elif "Overtime" in tds[0]:
                    current_period = "OT"
                elif len(tds) >= 4:
                    goal_period.append(current_period)
                    goal_team.append(tds[0])
                    goal_clock.append(tds[-1])

    # Convert goal clocks to float minutes
    goal_clock_float = []
    for i in range(len(goal_clock)):
        try:
            mins, secs = map(int, goal_clock[i].split(":"))
            if goal_period[i] == "2": mins += 20
            if goal_period[i] == "3": mins += 40
            if goal_period[i] == "OT": mins += 60
            goal_clock_float.append(mins + secs / 60)
        except:
            goal_clock_float.append(None)

    # ---------------------------
    # Penalty Info (DEFENSIVE)
    # ---------------------------
    penalties_period_1 = []
    penalties_period_2 = []
    penalties_period_3 = []
    penalties_overtime = []

    penalties_div = soup.find('div', id="penalties")
    if penalties_div:
        tbody = penalties_div.find('tbody')
        if tbody:
            tds = tbody.find_all('td')

            buckets = [
                penalties_period_1,
                penalties_period_2,
                penalties_period_3,
                penalties_overtime
            ]

            idx = 0
            for td in tds:
                text = td.text.strip()
                if split_phrase in text or split_phrase2 in text:
                    idx += 1
                elif text and idx < len(buckets):
                    buckets[idx].append(text)

    penalty_period = []
    penalty_team = []
    penalty_player = []
    penalty_minutes = []
    penalty_type = []
    penalty_clock = []

    def unpack(period_list, period_label):
        i = 0
        while i + 4 < len(period_list):
            penalty_period.append(period_label)
            penalty_team.append(period_list[i])
            penalty_player.append(period_list[i+1])
            penalty_minutes.append(period_list[i+2])
            penalty_type.append(period_list[i+3])
            penalty_clock.append(period_list[i+4])
            i += 5

    unpack(penalties_period_1, "1")
    unpack(penalties_period_2, "2")
    unpack(penalties_period_3, "3")
    unpack(penalties_overtime, "OT")

    # ---------------------------
    # Convert penalty clocks to float minutes
    # ---------------------------
    penalty_clock_float = []

    for i in range(len(penalty_clock)):
        clock = penalty_clock[i]

        if ":" not in clock:
            penalty_clock_float.append(None)
            continue

        try:
            mins, secs = map(int, clock.split(":"))
        except:
            penalty_clock_float.append(None)
            continue

        if penalty_period[i] == "2": mins += 20
        if penalty_period[i] == "3": mins += 40
        if penalty_period[i] == "OT": mins += 60

        penalty_clock_float.append(mins + secs / 60)

    # ---------------------------
    # Score at penalty
    # ---------------------------
    penalty_scores = []

    for pc in penalty_clock_float:
        if pc is None:
            penalty_scores.append("")
            continue

        home_goals = sum(
            1 for gtime, gteam in zip(goal_clock_float, goal_team)
            if gtime is not None and gtime <= pc and gteam == home_team
        )

        away_goals = sum(
            1 for gtime, gteam in zip(goal_clock_float, goal_team)
            if gtime is not None and gtime <= pc and gteam == away_team
        )

        penalty_scores.append(f"{away_goals}-{home_goals}")

    # ---------------------------
    # Build rows
    # ---------------------------
    for i in range(len(penalty_period)):
        all_rows.append({
            "Game ID": game_id,
            "Location": get_location(),
            "Game Type": game_type,
            "Date": date,
            "Home Team": home_team,
            "Away Team": away_team,
            "Conference": home_conf,
            "Referee 1": referee_names[0],
            "Referee 2": referee_names[1],
            "Period": penalty_period[i],
            "Team": penalty_team[i],
            "Player": penalty_player[i],
            "Minutes": penalty_minutes[i],
            "Type": penalty_type[i],
            "Game Clock": penalty_clock[i],
            "Score at Penalty": penalty_scores[i]
        })

df = pd.DataFrame(all_rows)

# Open your sheet
sheet = client.open("Hockey Penalties").sheet1

# Prevent duplicates
df = df.drop_duplicates()

# Clear old data
sheet.clear()

# Upload new data
sheet.update([df.columns.values.tolist()] + df.values.tolist())

print("Google Sheet updated successfully!")
